"""init migration

Revision ID: 6e97f032b121
Revises: 
Create Date: 2026-09-14 20:00:19.773579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e97f032b121'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_article_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('link', sa.String(length=2048), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'source', 'published_at', 'locale', name='uq_news_article_identity')
    )
    op.create_index(op.f('ix_news_article_data_locale'), 'news_article_data', ['locale'], unique=False)
    op.create_index(op.f('ix_news_article_data_published_at'), 'news_article_data', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_article_data_published_at'), table_name='news_article_data')
    op.drop_index(op.f('ix_news_article_data_locale'), table_name='news_article_data')
    op.drop_table('news_article_data')
    # ### end Alembic commands ###
