"""add llm_registry model

Revision ID: aefaf84dea8c
Revises: 1b23776a8992
Create Date: 2026-10-08 22:47:45.490622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aefaf84dea8c'
down_revision: Union[str, Sequence[str], None] = '1b23776a8992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_model_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=20), nullable=False),
    sa.Column('owned_by', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'owned_by', name='uq_llm_model_identity')
    )
    op.create_index(op.f('ix_llm_model_data_created_date'), 'llm_model_data', ['created_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_model_data_created_date'), table_name='llm_model_data')
    op.drop_table('llm_model_data')
    # ### end Alembic commands ###
